version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: python -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt || echo "No requirements.txt file found, skipping."
      - run:
          name: Run unit tests
          command: python -m unittest discover
workflows:
  version: 2
  test:
    jobs:
      - test
